### ISSUE TITLE
Ninja, Space Dragon, and Revenant spwaning needs to be adminlocked

### ISSUE THREAD

**Issue by PursuitInAshes** [Sector-Umbra/Sector-Umbra#119]
## Description
The GM team was in agreement that these should be locked to GM approval only. This means that the event scheduler should not spawn them in automatically, an admin should have to manually spawn the ghostrole/trigger the event

**Screenshots**
![image](https://github.com/user-attachments/assets/820fac0f-801f-423a-9597-7b036c032f11)

**Additional context**
All three should be fairly easy to disable on the yaml side of their events. Changing the max players is an _alright_ solution, but it would be better to remove them from the list of events the gamerule can use (The rule most umbra rounds use is `secretextended`, I don't know the proper backend name, but that should be close.)

**Comment by lunarcomets** [comment]
it for some reason we can’t use secretextended, we also use just normal extended, so should probably make sure to tweak the event scheduler there too

**Comment by Boaz1111** [comment]
so you still want to have the gamerule I assume? For addgamerule?

**Comment by Boaz1111** [comment]
I’ll have a look

**Comment by PolarTundraa** [comment]
Hiya, GM here, it wasn't included in the initial list but please in addition to what's currently being disabled, also disable the event scheduled automatically running the immovable rod event

**Comment by Boaz1111** [comment]
alrighty
