### ISSUE TITLE
Disable Contraband Indicators On Items

### ISSUE THREAD

**Issue by PursuitInAshes** [Sector-Umbra/Sector-Umbra#149]
## Description
The indicator telling you if something is contraband or not (When you examine it) should outright be disabled.

**Comment by deepdarkdepths** [comment]
Disable or reverted entirely?

**Comment by Coolsurf6** [comment]
Might there be a way to just disable it so any PRs adding more to it or functionality is just disabled while in game to not cause constant conflicts with git?

**Comment by TsjipTsjip** [comment]
The way I want to do this is to just disable the lines of code that inject the description lines.

**Comment by MissKay1994** [comment]
Unless I'm mistaken, I recall it being mentioned there is a cvar to disable the tags

**Comment by TsjipTsjip** [comment]
Solved by CVar tweak server-sided. For those interested, the CVar is `game.contraband_examine`.
