### ISSUE TITLE
Anomalous infections need to be disabled pending a refactor

### ISSUE THREAD

**Issue by TsjipTsjip** [Sector-Umbra/Sector-Umbra#159]
## Description

These events only add in a very significant way to the chaos factor and while allowing people to continue working while being infected is an option is an option, this event is not fit for our setting.

On the other hand, if the only option is killing these anomalies as soon as it's noticed, this event serves no purpose.

To conclude, either way, this event serves no purpose on our server and it needs to be disabled/removed.

**Comment by Boaz1111** [comment]
@TsjipTsjip from both random events and anomaly gen, yes?

**Comment by Kukutis96513** [comment]
should probably close this issue since #163 got merged
