### ISSUE TITLE
Remove references of CD's Lost and Found Locker

### ISSUE THREAD

**Issue by PursuitInAshes** [Sector-Umbra/Sector-Umbra#218]
## Description
We don't maintain it nor use it anywhere, its unneeded in our codebase.

Don't forget to write a migration entry to make the locker null.

![image](https://github.com/user-attachments/assets/3a22e6df-2b14-45b7-a4fe-b4ba60b1ae45)

**Comment by Coolsurf6** [comment]
Already completed.
