### ISSUE TITLE
Vulpkanins cannot have gauze overlay markings

### ISSUE THREAD

**Issue by TsjipTsjip** [Sector-Umbra/Sector-Umbra#232]
## Description

Title. Probably forgotten about. Potentially a CD issue?

**Comment by PursuitInAshes** [comment]
Definitely an oversight when I ported vulps to CD. I'll add it to my list to fix, though it should be pretty straight forward if anyone wants to take a look at it.

**Comment by PursuitInAshes** [comment]
CD PR 495 will fix this. Once we merge this it can be closed.

**Comment by PursuitInAshes** [comment]
CD PR is merged, going to close this as we'll include it in the next upstream merge.
