### ISSUE TITLE
Meta Station is Missing Some Senior Roles

### ISSUE THREAD

**Issue by Nairodian** [Sector-Umbra/Sector-Umbra#234]
## Description
From a glance it appears that Meta is missing Senior Officer, Senior Physician, and Senior Researcher.

**Additional context**
Might actually be all of them, I'm assuming this senior engineer slot I'm seeing was added by a GM given the prototype file:
![image](https://github.com/user-attachments/assets/5c6ee556-0e3c-4d04-b766-1e694e8b624d)

**Comment by Boaz1111** [comment]
The senior engineer slot was indeed added by a GM
