### ISSUE TITLE
CMO PDA Bug?

### ISSUE THREAD

**Issue by ColdDead** [Sector-Umbra/Sector-Umbra#53]
## Description

I can not Scann with CMO PDA peopel but i not see the damge "interface" what damge it have.
Doenst matter what PDA i get spawn in, it only work with the Default Healt Analyser
**Reproduction**

Spawn As CMO and use you PDA on you self/other person (I dont know when this not work how reproduce)

**Screenshots**

![SS14 Loader_rXHaRdG4cy](https://github.com/Sector-Umbra/Sector-Umbra/assets/38980900/aa3a8bd5-ea5c-45e0-9a94-b7edfcc17a6f)
![SS14 Loader_XnNgmnD4kz](https://github.com/Sector-Umbra/Sector-Umbra/assets/38980900/357b57e5-c86c-4927-b099-3775ce8e3753)
![SS14 Loader_p1EN0cA7B9](https://github.com/Sector-Umbra/Sector-Umbra/assets/38980900/579cf063-9473-40fd-bda8-d74286cfab92)

**Additional context**

The picture are all after i scanned with the item on my hands. First one is CMO, 2 one a Doctor spawned in PDA. Last one the default medic vendor scanner

**Comment by TsjipTsjip** [comment]
Related upstream issue: https://github.com/space-wizards/space-station-14/issues/28275

**Comment by TsjipTsjip** [comment]
Resolved by upstream.
