### ISSUE TITLE
Missing Dwarven Haircuts

### ISSUE THREAD

**Issue by Kezu02** [Sector-Umbra/Sector-Umbra#74]
## Description

Right now, dwarves seem to have forgotten most of the possible ways they can style their hair.

**Screenshots**

![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/143474299/ce702621-9b07-4eb0-8b29-2bce8743fa0d)

**Comment by luckyshotpictures** [comment]
fixed by #95
